version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ebos-api-app
    container_name: app-ebos
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: secret
      DB_DATABASE: ebos-api
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: ebos-api-nginx 
    container_name: webserver-ebos
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app  

  db:
    image: mysql:8.0
    # command: 
      # - ./init.sql:/data/application/init.sql
      # - mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ebos-db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ebos-api
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ebos-db-admin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80

volumes:
  dbdata:   
    driver: local 